program : branchloop branchloop2 branchloop3

branchloop : branchloop.c
	gcc -o branchloop branchloop.c

branchloop2 : branchloop2.c
	gcc -o branchloop2 branchloop2.c

branchloop3 : branchloop3.c
	gcc -o branchloop3 branchloop3.c
